# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nhx5dcF1RW7UwxBkFZJlbq4P2DxCP5HB
"""

#import numpy, pandas, matplotlib, seaborn libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd

# Accessing the file using the correct key 'Big_Mart_Sales.csv'
df = pd.read_csv(io.BytesIO(uploaded['Big_Mart_Sales.csv']))
# Now you can work with the dataframe 'df'
print(df.head())

#print the top 5 rows of the dataset

print(df.head())

#check if there are any null values in the uploaded dataset

# Check for null values in each column
print(df.isnull().sum())

#clear the null values in the Item_Weight column using mean imputation technique

# Calculate the mean of 'Item_Weight' column, ignoring NaN values
mean_item_weight = df['Item_Weight'].mean()

# Fill NaN values in 'Item_Weight' with the calculated mean
df['Item_Weight'].fillna(mean_item_weight, inplace=True)

# Verify that null values are filled
print(df.isnull().sum())

#clear the null values in Outlet_Size using the mode imputation technique

# Fill missing values in 'Outlet_Size' with the mode
outlet_size_mode = df['Outlet_Size'].mode()[0]
df['Outlet_Size'].fillna(outlet_size_mode, inplace=True)

# Verify that null values are filled
print(df.isnull().sum())

#create a distribution plot for Item_Weight, Item_Visibility, Item_MRP and Item_Sales

import matplotlib.pyplot as plt
import seaborn as sns

# Create the distribution plots
plt.figure(figsize=(12, 8))

plt.subplot(2, 2, 1)
sns.distplot(df['Item_Weight'])
plt.title('Item Weight Distribution')

plt.subplot(2, 2, 2)
sns.distplot(df['Item_Visibility'])
plt.title('Item Visibility Distribution')

plt.subplot(2, 2, 3)
sns.distplot(df['Item_MRP'])
plt.title('Item MRP Distribution')

plt.subplot(2, 2, 4)
sns.distplot(df['Item_Outlet_Sales'])
plt.title('Item Sales Distribution')

plt.tight_layout()
plt.show()

# prompt: create a countplot for Outlet_Establishment_Year, Item_Fat_Content, Item_Type

# Create countplots for Outlet_Establishment_Year, Item_Fat_Content, and Item_Type
plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
sns.countplot(x='Outlet_Establishment_Year', data=df)
plt.title('Outlet Establishment Year Countplot')

plt.subplot(1, 3, 2)
sns.countplot(x='Item_Fat_Content', data=df)
plt.title('Item Fat Content Countplot')

plt.subplot(1, 3, 3)
sns.countplot(x='Item_Type', data=df)
plt.xticks(rotation=90) # Rotate x-axis labels for better readability
plt.title('Item Type Countplot')

plt.tight_layout()
plt.show()

"""Data Preprocessing:

"""

df['Item_Fat_Content'].value_counts()

df.replace({'Item_Fat_Content':{'low fat': 'Low Fat','LF':'Low Fat', 'reg': 'Regular'}}, inplace=True)

df['Item_Fat_Content'].value_counts()

"""Label Encoder"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# Encode the specified columns
df['Item_Identifier'] = le.fit_transform(df['Item_Identifier'])
df['Item_Fat_Content'] = le.fit_transform(df['Item_Fat_Content'])
df['Item_Type'] = le.fit_transform(df['Item_Type'])
df['Outlet_Identifier'] = le.fit_transform(df['Outlet_Identifier'])
df['Outlet_Size'] = le.fit_transform(df['Outlet_Size'])
df['Outlet_Type'] = le.fit_transform(df['Outlet_Type'])
df['Outlet_Location_Type'] = le.fit_transform(df['Outlet_Location_Type'])

df.head()

x=df.drop(columns='Item_Outlet_Sales', axis=1)
y=df['Item_Outlet_Sales']

x

y

"""Splitting the data into Training Data and Testing Data"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train)
print(x_test)
print(y_train)
y_test

"""Regression Model

"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the Linear Regression model
model = LinearRegression()

# Train the model on the training data
model.fit(x_train, y_train)

# Make predictions on the test data
y_pred = model.predict(x_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

"""Here we are not getting very good accuracy with the linear regression model. Hence we are going for XGBoost regressor"""

from flask import Flask

# prompt: generate the code for exporting the model to a website using flask

import pickle
from flask import Flask, request, jsonify

# Assuming your trained model is stored in 'model.pkl'
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json()
        # Assuming the input data is a dictionary with keys matching your feature names
        # Extract features from the request data
        features = [data['Item_Identifier'], data['Item_Weight'], data['Item_Fat_Content'],
                    data['Item_Visibility'], data['Item_Type'], data['Item_MRP'],
                    data['Outlet_Identifier'], data['Outlet_Establishment_Year'],
                    data['Outlet_Size'], data['Outlet_Location_Type'], data['Outlet_Type']]

        # Make a prediction using your loaded model
        prediction = model.predict([features])

        return jsonify({'prediction': prediction[0]})

    except Exception as e:
        return jsonify({'error': str(e)})

if __name__ == '__main__':
    app.run(debug=True)

# prompt: create the url for the above exported model

from flask import Flask, request, jsonify
import pickle

app = Flask(__name__)

# Load the trained model
with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json()
        # Assuming the input data is a dictionary with keys matching your feature names
        # Extract features from the request data
        features = [data['Item_Identifier'], data['Item_Weight'], data['Item_Fat_Content'],
                    data['Item_Visibility'], data['Item_Type'], data['Item_MRP'],
                    data['Outlet_Identifier'], data['Outlet_Establishment_Year'],
                    data['Outlet_Size'], data['Outlet_Location_Type'], data['Outlet_Type']]

        # Make a prediction using your loaded model
        prediction = model.predict([features])

        return jsonify({'prediction': prediction[0]})

    except Exception as e:
        return jsonify({'error': str(e)})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000) # Added host and port

#The URL to access the prediction endpoint would be:  http://<your_colab_ip_address>:5000/predict
#To find your Colab ip address, run the following commands in a separate code cell.













